### ISSUE TITLE
Can't start trial in DataGraph plugin for IntelliJ IDEA Ultimate 2023.3

### ISSUE THREAD

**Issue by ar-IGT** [AntonShuvaev/intellij-datagraph#2]
After installing plugin, either from disk or from Plugin Marketplace inside of IDEA, I see no option to start a 30-days trial.

**Environment information:**
- OS: Window 10 Enterprise 10.0.19045
- IDE version: 2023.3 (233.11799.241)
- plugin version: DataGraph 1.0.5-233

**Comment by AntonShuvaev** [comment]
To activate trial, please go to `Help > Register... > Select DataGraph plugin > Activate New License > Start trial`

**Comment by ar-IGT** [comment]
Ok, it worked, thank you!
