### ISSUE TITLE
The graph is not displayed

### ISSUE THREAD

**Issue by olton** [AntonShuvaev/intellij-datagraph#3]
<img width="582" alt="image" src="https://github.com/AntonShuvaev/intellij-datagraph/assets/365108/6cfa7c02-e173-4005-9180-2c7965c4d9a3">

**Describe the bug**
The Graph is not displayed

**Steps to reproduce**
1. Install datagraph
2. Activate Trial
3. Open any JSON file

**Environment information:**
- OS: Windows 11
WebStorm 2023.3
Build #WS-233.11799.229, built on December 1, 2023
Licensed to Metro UI CSS / Serhii Pimenov
Subscription is active until April 16, 2024.
For non-commercial open source development only.
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  CMD Support (1.0.5)
  Batch Scripts Support (1.0.13)
  com.intellij.apacheConfig (233.11799.244)
  com.intellij.ml.llm (233.11799.241)
  org.jetbrains.plugins.stylus (233.11799.172)
  com.datagraph (1.0.5-233)
  ru.adelf.idea.dotenv (2023.3)
  org.jetbrains.plugins.docker.gateway (233.11799.244)
  com.intellij.grazie.pro (0.3.266)
  org.jetbrains.plugins.astro (233.11799.172)
  me.serce.solidity (2.4.3)
  mdx.js (233.11799.172)
  com.intellij.database (233.11799.229)
  izhangzhihao.rainbow.brackets (2023.3.9-233)

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. Will take a look into it. As a workaround you can try to restart IDE.
