### ISSUE TITLE
The graphs based on JSON data exported from saved profiles data of Google Chrome Developer Tools Performance tab aren't prepared at all

### ISSUE THREAD

**Issue by ar-IGT** [AntonShuvaev/intellij-datagraph#4]
I recorded performance profile of my web application logging out functionality using Google Chrome Developer Tools Performance tab tool.

Exported JSON data for three different tabs of my web app is between 3 and 4 MB of each file.

When I try to visualize this data into diagrams using DataGraph in my IntelliJ IDEA Ultimate, it just keeps loading forever.

Do DataGraph can visualize JSON data exported from Chrome's Performance profiling?

**Environment information:**
- OS: Window 10 Enterprise 10.0.19045
- IDE version: 2023.3 (233.11799.241)
- plugin version: DataGraph 1.0.5-233

**Comment by ar-IGT** [comment]
I've stumbled upon Catapult Trace-Viewer (https://chromium.googlesource.com/catapult/+/HEAD/tracing/README.md) tool from Chromium project, but it doesn't convert dumped JSON data into PUML diagrams, unfortunately.

**Comment by AntonShuvaev** [comment]
There is no strict limit on file size or the count of JSON nodes, but files with a large number of nodes may not open successfully. For instance, the exported JSON from the Google Chrome Profiler, despite being only 3 MB in size, contains a significant number of nodes. Unfortunately, this means it cannot be opened with the plugin. As a workaround, you can manually split the file into separate files.

**Comment by AntonShuvaev** [comment]
I've made performance improvements to the plugin. You should now be able to open large JSON files without issues.
